// SXWallGenerator.cpp

#include "Stage/SXWallGenerator.h"

#include "Components/HierarchicalInstancedStaticMeshComponent.h"
#include "Components/SceneComponent.h"

ASXWallGenerator::ASXWallGenerator()
{
	PrimaryActorTick.bCanEverTick = false;

	SceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("SceneRoot"));
	SetRootComponent(SceneRoot);

	StraightWallHISM = CreateDefaultSubobject<UHierarchicalInstancedStaticMeshComponent>(TEXT("StraightWallHISM"));
	StraightWallHISM->SetupAttachment(SceneRoot);
	StraightWallHISM->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	StraightWallHISM->SetCollisionObjectType(ECC_WorldStatic);
	StraightWallHISM->SetCollisionResponseToAllChannels(ECR_Block);

	CornerWallHISM = CreateDefaultSubobject<UHierarchicalInstancedStaticMeshComponent>(TEXT("CornerWallHISM"));
	CornerWallHISM->SetupAttachment(SceneRoot);
	CornerWallHISM->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	CornerWallHISM->SetCollisionObjectType(ECC_WorldStatic);
	CornerWallHISM->SetCollisionResponseToAllChannels(ECR_Block);

	EntranceWallHISM = CreateDefaultSubobject<UHierarchicalInstancedStaticMeshComponent>(TEXT("EntranceWallHISM"));
	EntranceWallHISM->SetupAttachment(SceneRoot);
	EntranceWallHISM->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	EntranceWallHISM->SetCollisionObjectType(ECC_WorldStatic);
	EntranceWallHISM->SetCollisionResponseToAllChannels(ECR_Block);

	SouthWestCornerTransform.BaseYaw = 0.0f;
	SouthEastCornerTransform.BaseYaw = -90.0f;
	NorthWestCornerTransform.BaseYaw = 90.0f;
	NorthEastCornerTransform.BaseYaw = 180.0f;
}

void ASXWallGenerator::OnConstruction(const FTransform& Transform)
{
	Super::OnConstruction(Transform);

	if (bGenerateOnConstruction)
	{
		RebuildWalls();
	}
}

void ASXWallGenerator::RebuildWalls()
{
	ClearWalls();

	WidthSegments = FMath::Max(1, WidthSegments);
	HeightSegments = FMath::Max(1, HeightSegments);
	SegmentLength = FMath::Max(1.0f, SegmentLength);

	BuildHorizontalSide(true);
	BuildHorizontalSide(false);
	BuildVerticalSide(true);
	BuildVerticalSide(false);
}

void ASXWallGenerator::ClearWalls()
{
	if (IsValid(StraightWallHISM))
	{
		StraightWallHISM->ClearInstances();
	}

	if (IsValid(CornerWallHISM))
	{
		CornerWallHISM->ClearInstances();
	}

	if (IsValid(EntranceWallHISM))
	{
		EntranceWallHISM->ClearInstances();
	}
}

void ASXWallGenerator::BuildHorizontalSide(bool bNorth)
{
	const ESXWallEntranceSide Side = bNorth ? ESXWallEntranceSide::North : ESXWallEntranceSide::South;
	const float HalfWidth = WidthSegments * SegmentLength * 0.5f;
	const float HalfHeight = HeightSegments * SegmentLength * 0.5f;
	const float Y = bNorth ? HalfHeight : -HalfHeight;
	const float Yaw = bNorth ? 180.0f : 0.0f;

	for (int32 XIndex = 0; XIndex < WidthSegments; ++XIndex)
	{
		const bool bCornerSegment = XIndex == 0 || XIndex == WidthSegments - 1;
		const float X = bCenteredOnActor
			? (-HalfWidth + SegmentLength * 0.5f + XIndex * SegmentLength)
			: (SegmentLength * 0.5f + XIndex * SegmentLength);

		const FSXWallEntranceData* EntranceData = nullptr;
		if (IsEntranceSegment(Side, XIndex, WidthSegments, EntranceData))
		{
			if (bUseEntranceWallMesh && EntranceData != nullptr && EntranceData->bUseEntranceWallMesh && IsValid(EntranceWallHISM))
			{
				AddWallInstance(EntranceWallHISM, EntranceWallTransform, FVector(X, Y, WallZOffset), Yaw);
			}
			continue;
		}

		if (bUseCornerWallMesh && bCornerSegment && IsValid(CornerWallHISM))
		{
			const FSXWallCornerTransformSettings& CornerTransformSettings = bNorth
				? (XIndex == 0 ? NorthWestCornerTransform : NorthEastCornerTransform)
				: (XIndex == 0 ? SouthWestCornerTransform : SouthEastCornerTransform);
			AddCornerWallInstance(CornerTransformSettings, FVector(X, Y, WallZOffset));
			continue;
		}

		AddWallInstance(StraightWallHISM, StraightWallTransform, FVector(X, Y, WallZOffset), Yaw);
	}
}

void ASXWallGenerator::BuildVerticalSide(bool bEast)
{
	const ESXWallEntranceSide Side = bEast ? ESXWallEntranceSide::East : ESXWallEntranceSide::West;
	const float HalfWidth = WidthSegments * SegmentLength * 0.5f;
	const float HalfHeight = HeightSegments * SegmentLength * 0.5f;
	const float X = bEast ? HalfWidth : -HalfWidth;
	const float Yaw = bEast ? -90.0f : 90.0f;

	for (int32 YIndex = 0; YIndex < HeightSegments; ++YIndex)
	{
		const bool bCornerSegment = YIndex == 0 || YIndex == HeightSegments - 1;
		if (bCornerSegment && bUseCornerWallMesh)
		{
			// Corners are generated by the horizontal sides to avoid duplicates.
			continue;
		}

		const float Y = bCenteredOnActor
			? (-HalfHeight + SegmentLength * 0.5f + YIndex * SegmentLength)
			: (SegmentLength * 0.5f + YIndex * SegmentLength);

		const FSXWallEntranceData* EntranceData = nullptr;
		if (IsEntranceSegment(Side, YIndex, HeightSegments, EntranceData))
		{
			if (bUseEntranceWallMesh && EntranceData != nullptr && EntranceData->bUseEntranceWallMesh && IsValid(EntranceWallHISM))
			{
				AddWallInstance(EntranceWallHISM, EntranceWallTransform, FVector(X, Y, WallZOffset), Yaw);
			}
			continue;
		}

		AddWallInstance(StraightWallHISM, StraightWallTransform, FVector(X, Y, WallZOffset), Yaw);
	}
}

void ASXWallGenerator::AddWallInstance(UHierarchicalInstancedStaticMeshComponent* TargetComponent, const FSXWallInstanceTransformSettings& TransformSettings, const FVector& Location, float YawDegrees) const
{
	if (IsValid(TargetComponent) == false)
	{
		return;
	}

	FRotator FinalRotation = TransformSettings.RotationOffset;
	FinalRotation.Yaw += YawDegrees;

	const FVector FinalLocation = Location + FinalRotation.RotateVector(TransformSettings.LocationOffset);
	const FTransform InstanceTransform(FinalRotation, FinalLocation, TransformSettings.Scale);
	TargetComponent->AddInstance(InstanceTransform);
}

void ASXWallGenerator::AddCornerWallInstance(const FSXWallCornerTransformSettings& CornerTransformSettings, const FVector& Location) const
{
	if (IsValid(CornerWallHISM) == false)
	{
		return;
	}

	FSXWallInstanceTransformSettings CombinedTransform;
	CombinedTransform.LocationOffset = CornerWallTransform.LocationOffset + CornerTransformSettings.Transform.LocationOffset;
	CombinedTransform.RotationOffset = CornerWallTransform.RotationOffset + CornerTransformSettings.Transform.RotationOffset;
	CombinedTransform.Scale = FVector(
		CornerWallTransform.Scale.X * CornerTransformSettings.Transform.Scale.X,
		CornerWallTransform.Scale.Y * CornerTransformSettings.Transform.Scale.Y,
		CornerWallTransform.Scale.Z * CornerTransformSettings.Transform.Scale.Z
	);

	AddWallInstance(CornerWallHISM, CombinedTransform, Location, CornerTransformSettings.BaseYaw);
}

bool ASXWallGenerator::IsEntranceSegment(ESXWallEntranceSide Side, int32 SegmentIndex, int32 SegmentCount, const FSXWallEntranceData*& OutEntranceData) const
{
	OutEntranceData = nullptr;

	for (const FSXWallEntranceData& EntranceData : Entrances)
	{
		if (EntranceData.Side != Side)
		{
			continue;
		}

		const int32 StartIndex = ResolveEntranceStartIndex(EntranceData, SegmentCount);
		const int32 EndIndex = StartIndex + FMath::Max(1, EntranceData.SegmentWidth) - 1;
		if (SegmentIndex >= StartIndex && SegmentIndex <= EndIndex)
		{
			OutEntranceData = &EntranceData;
			return true;
		}
	}

	return false;
}

int32 ASXWallGenerator::ResolveEntranceStartIndex(const FSXWallEntranceData& EntranceData, int32 SegmentCount) const
{
	const int32 EntranceWidth = FMath::Max(1, EntranceData.SegmentWidth);
	const int32 MaxStartIndex = FMath::Max(0, SegmentCount - EntranceWidth);

	if (EntranceData.SegmentIndex <= 0)
	{
		return FMath::Clamp((SegmentCount - EntranceWidth) / 2, 0, MaxStartIndex);
	}

	return FMath::Clamp(EntranceData.SegmentIndex, 0, MaxStartIndex);
}
